/**
 * config.js
 * ─────────────────────────────────────────────────────────
 * Central configuration for MedPredict.
 * Holds the embedded dataset, min/max normalization bounds,
 * the neighbourhood list, the brain.js network instance,
 * and the current toggle-button state.
 *
 * Source: KaggleV2-May-2016.csv
 * https://www.kaggle.com/joniarroba/noshowappointments
 * (150 rows used to avoid browser performance issues)
 * ─────────────────────────────────────────────────────────
 */

/* ── Raw dataset (150 rows, preprocessed from CSV) ──────── */
export const RAW_DATA = [
  {"gender":0,"age":62,"neighbourhood":"JARDIM DA PENHA","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":56,"neighbourhood":"JARDIM DA PENHA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":62,"neighbourhood":"MATA DA PRAIA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":8,"neighbourhood":"PONTAL DE CAMBURI","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":56,"neighbourhood":"JARDIM DA PENHA","scholarship":0,"hipertension":1,"diabetes":1,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":76,"neighbourhood":"REPÚBLICA","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":0},
  {"gender":0,"age":23,"neighbourhood":"GOIABEIRAS","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":1},
  {"gender":0,"age":39,"neighbourhood":"GOIABEIRAS","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":1},
  {"gender":0,"age":21,"neighbourhood":"ANDORINHAS","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":19,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":0},
  {"gender":0,"age":30,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":0},
  {"gender":1,"age":29,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":2,"noshow":1},
  {"gender":0,"age":22,"neighbourhood":"NOVA PALESTINA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":28,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":54,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":15,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":2,"noshow":0},
  {"gender":1,"age":50,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":40,"neighbourhood":"CONQUISTA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":1},
  {"gender":0,"age":30,"neighbourhood":"NOVA PALESTINA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":2,"noshow":0},
  {"gender":0,"age":46,"neighbourhood":"DA PENHA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":30,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":1},
  {"gender":0,"age":4,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":1},
  {"gender":1,"age":13,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":3,"noshow":1},
  {"gender":0,"age":46,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":65,"neighbourhood":"TABUAZEIRO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":46,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":2,"noshow":0},
  {"gender":0,"age":45,"neighbourhood":"BENTO FERREIRA","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":4,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":0},
  {"gender":1,"age":51,"neighbourhood":"SÃO PEDRO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":32,"neighbourhood":"SANTA MARTHA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":46,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":0},
  {"gender":1,"age":12,"neighbourhood":"NOVA PALESTINA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":1},
  {"gender":1,"age":61,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":38,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":3,"noshow":0},
  {"gender":0,"age":79,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":18,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":63,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":1,"diabetes":1,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":64,"neighbourhood":"TABUAZEIRO","scholarship":1,"hipertension":1,"diabetes":1,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":85,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":8,"noshow":0},
  {"gender":0,"age":59,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":55,"neighbourhood":"TABUAZEIRO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":71,"neighbourhood":"MARUÍPE","scholarship":0,"hipertension":0,"diabetes":1,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":50,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":49,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":78,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":1,"diabetes":1,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":1},
  {"gender":0,"age":31,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":58,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":1,"handcap":0,"sms_received":1,"days_wait":3,"noshow":0},
  {"gender":0,"age":39,"neighbourhood":"MARUÍPE","scholarship":0,"hipertension":1,"diabetes":1,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":58,"neighbourhood":"SÃO CRISTÓVÃO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":2,"noshow":1},
  {"gender":0,"age":27,"neighbourhood":"GRANDE VITÓRIA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":28,"noshow":1},
  {"gender":0,"age":19,"neighbourhood":"GRANDE VITÓRIA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":28,"noshow":1},
  {"gender":0,"age":23,"neighbourhood":"GRANDE VITÓRIA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":28,"noshow":1},
  {"gender":0,"age":23,"neighbourhood":"GRANDE VITÓRIA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":28,"noshow":1},
  {"gender":1,"age":6,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":6,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":2,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":12,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":9,"noshow":1},
  {"gender":1,"age":11,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":7,"neighbourhood":"SÃO PEDRO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":0,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":8,"neighbourhood":"NOVA PALESTINA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":0},
  {"gender":0,"age":2,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":1},
  {"gender":0,"age":3,"neighbourhood":"CONQUISTA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":3,"noshow":0},
  {"gender":1,"age":0,"neighbourhood":"SÃO BENEDITO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":0},
  {"gender":1,"age":0,"neighbourhood":"ILHA DAS CAIEIRAS","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":3,"noshow":0},
  {"gender":1,"age":0,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":1,"noshow":0},
  {"gender":1,"age":1,"neighbourhood":"CONQUISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":0,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":69,"neighbourhood":"JARDIM DA PENHA","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":22,"noshow":0},
  {"gender":0,"age":58,"neighbourhood":"SANTO ANDRÉ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":22,"noshow":0},
  {"gender":1,"age":62,"neighbourhood":"SOLON BORGES","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":22,"noshow":0},
  {"gender":0,"age":30,"neighbourhood":"BONFIM","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":22,"noshow":0},
  {"gender":0,"age":61,"neighbourhood":"JARDIM CAMBURI","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":68,"neighbourhood":"REPÚBLICA","scholarship":0,"hipertension":1,"diabetes":1,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":22,"noshow":0},
  {"gender":0,"age":64,"neighbourhood":"MARIA ORTIZ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":10,"noshow":0},
  {"gender":0,"age":60,"neighbourhood":"JABOUR","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":10,"noshow":0},
  {"gender":1,"age":28,"neighbourhood":"ANTÔNIO HONÓRIO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":10,"noshow":1},
  {"gender":0,"age":27,"neighbourhood":"JABOUR","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":21,"neighbourhood":"MARIA ORTIZ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":10,"noshow":0},
  {"gender":1,"age":67,"neighbourhood":"MARIA ORTIZ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":10,"noshow":1},
  {"gender":1,"age":68,"neighbourhood":"JABOUR","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":10,"noshow":0},
  {"gender":0,"age":49,"neighbourhood":"JABOUR","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":10,"noshow":0},
  {"gender":1,"age":71,"neighbourhood":"JABOUR","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":36,"neighbourhood":"RESISTÊNCIA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":29,"neighbourhood":"RESISTÊNCIA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":69,"neighbourhood":"RESISTÊNCIA","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":2,"noshow":0},
  {"gender":1,"age":10,"neighbourhood":"ILHA DE SANTA MARIA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":10,"noshow":0},
  {"gender":1,"age":2,"neighbourhood":"ILHA DE SANTA MARIA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":10,"noshow":0},
  {"gender":1,"age":1,"neighbourhood":"JUCUTUQUARA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":10,"noshow":0},
  {"gender":1,"age":0,"neighbourhood":"MONTE BELO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":11,"neighbourhood":"JUCUTUQUARA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":10,"noshow":1},
  {"gender":0,"age":10,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":9,"noshow":0},
  {"gender":1,"age":2,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":1,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":10,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":1,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":3,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":2,"noshow":0},
  {"gender":0,"age":35,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":17,"noshow":0},
  {"gender":0,"age":51,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":16,"noshow":0},
  {"gender":0,"age":1,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":20,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":16,"noshow":0},
  {"gender":1,"age":0,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":54,"neighbourhood":"MÁRIO CYPRESTE","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":50,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":0,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":1},
  {"gender":1,"age":51,"neighbourhood":"BELA VISTA","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":54,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":26,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":8,"noshow":1},
  {"gender":0,"age":38,"neighbourhood":"BELA VISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":34,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":16,"noshow":0},
  {"gender":0,"age":34,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":16,"noshow":0},
  {"gender":0,"age":56,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":16,"noshow":0},
  {"gender":0,"age":59,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":1,"diabetes":1,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":10,"noshow":0},
  {"gender":1,"age":8,"neighbourhood":"NOVA PALESTINA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":9,"noshow":0},
  {"gender":0,"age":15,"neighbourhood":"BELA VISTA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":13,"noshow":0},
  {"gender":0,"age":54,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":18,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":16,"noshow":1},
  {"gender":0,"age":34,"neighbourhood":"SANTO ANTÔNIO","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":27,"noshow":0},
  {"gender":0,"age":35,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":27,"noshow":0},
  {"gender":0,"age":33,"neighbourhood":"MÁRIO CYPRESTE","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":23,"noshow":0},
  {"gender":0,"age":16,"neighbourhood":"MÁRIO CYPRESTE","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":13,"noshow":0},
  {"gender":0,"age":18,"neighbourhood":"MÁRIO CYPRESTE","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":27,"noshow":0},
  {"gender":1,"age":46,"neighbourhood":"BELA VISTA","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":31,"neighbourhood":"BELA VISTA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":2,"noshow":1},
  {"gender":0,"age":7,"neighbourhood":"SANTO ANTÔNIO","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":36,"neighbourhood":"MÁRIO CYPRESTE","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":23,"noshow":0},
  {"gender":0,"age":67,"neighbourhood":"PRAIA DO SUÁ","scholarship":0,"hipertension":0,"diabetes":1,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":1},
  {"gender":1,"age":42,"neighbourhood":"PRAIA DO SUÁ","scholarship":0,"hipertension":1,"diabetes":1,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":20,"noshow":0},
  {"gender":0,"age":34,"neighbourhood":"PRAIA DO SUÁ","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":16,"noshow":1},
  {"gender":0,"age":22,"neighbourhood":"PRAIA DO SUÁ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":20,"noshow":1},
  {"gender":0,"age":5,"neighbourhood":"SANTA HELENA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":29,"neighbourhood":"PRAIA DO SUÁ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":1,"handcap":0,"sms_received":0,"days_wait":0,"noshow":1},
  {"gender":1,"age":0,"neighbourhood":"PRAIA DO SUÁ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":20,"noshow":1},
  {"gender":1,"age":69,"neighbourhood":"PRAIA DO SUÁ","scholarship":0,"hipertension":0,"diabetes":1,"alcoholism":1,"handcap":0,"sms_received":0,"days_wait":14,"noshow":0},
  {"gender":1,"age":47,"neighbourhood":"PRAIA DO SUÁ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":10,"noshow":0},
  {"gender":1,"age":30,"neighbourhood":"PRAIA DO SUÁ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":20,"noshow":1},
  {"gender":0,"age":33,"neighbourhood":"BONFIM","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":13,"noshow":1},
  {"gender":1,"age":18,"neighbourhood":"DA PENHA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":13,"noshow":1},
  {"gender":0,"age":29,"neighbourhood":"DA PENHA","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":9,"noshow":0},
  {"gender":1,"age":30,"neighbourhood":"DA PENHA","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":17,"neighbourhood":"BONFIM","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":15,"noshow":1},
  {"gender":1,"age":15,"neighbourhood":"DA PENHA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":14,"noshow":0},
  {"gender":1,"age":36,"neighbourhood":"DA PENHA","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":1,"days_wait":13,"noshow":0},
  {"gender":0,"age":36,"neighbourhood":"MARIA ORTIZ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":50,"neighbourhood":"MARIA ORTIZ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":1,"age":17,"neighbourhood":"ITARARÉ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":1},
  {"gender":0,"age":46,"neighbourhood":"INHANGUETÁ","scholarship":1,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":65,"neighbourhood":"UNIVERSITÁRIO","scholarship":0,"hipertension":1,"diabetes":0,"alcoholism":0,"handcap":1,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":62,"neighbourhood":"ITARARÉ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0},
  {"gender":0,"age":16,"neighbourhood":"ITARARÉ","scholarship":0,"hipertension":0,"diabetes":0,"alcoholism":0,"handcap":0,"sms_received":0,"days_wait":0,"noshow":0}
];

/* ── Normalization bounds (computed from RAW_DATA) ────────── */
export const configuration = {
  age:      { min: Infinity, max: -Infinity },
  days:     { min: Infinity, max: -Infinity },
  hoods:    []   // populated by initConfiguration()
};

/* ── Brain.js network instance ────────────────────────────── */
export const myBrain = {
  trainingData: [],
  net: new brain.NeuralNetwork({
    hiddenLayers: [10, 6],
    activation: 'sigmoid'
  })
};

/* ── UI toggle state ──────────────────────────────────────── */
export const toggleState = {
  gender: 'F',
  sms:    'No',
  schl:   'No',
  ht:     'No',
  db:     'No',
  al:     'No'
};
